on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    container: aruneko/texlive
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
      - name: Build a PDF file by latexmk
        run: latexmk main.tex
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf
